---
- name: Configure Prometheus data source and import dashboard in Grafana
  hosts: server2
  become: yes

  # Include variable file
  vars_files:
    - vars.yml
  # vars.yml




  tasks:
    - name: Create/Update Data sources
      grafana.grafana.datasource:
        datasource: |
          {
            "name": "Prometheus",
            "type": "prometheus",
            "access": "proxy",
            "url": "http://vmbackup.westeurope.cloudapp.azure.com:9090",
            "basicAuth": true,
            "basicAuthUser": "admin",
            "basicAuthPassword": "admin",
            "jsonData": {
              "httpMethod": "POST",
              "manageAlerts": true,
              "prometheusType": "Prometheus",
              "cacheLevel": "High"
            }
          }
        grafana_url: "{{ grafana_url }}"
        grafana_api_key: "{{ grafana_api_key }}"
        state: present

    - name: Delete Data sources
      grafana.grafana.datasource:
        datasource: "{{ lookup('ansible.builtin.file', 'datasource.json') }}"
        grafana_url: "{{ grafana_url }}"
        grafana_api_key: "{{ grafana_api_key }}"
        state: absent
